### ISSUE TITLE
[Platform] Change Binance api from explorer to RPC 

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1003]
Explorer api is outdated, let's use RPC to prevent issues like constant fails of explorer

**Comment by kolya182** [comment]
RPC not meant to serve as a source of transactions, it only keep history for 24 hours or so 
https://dex.binance.org/api/v1/transactions?address=bnb1xwalxpaes9r0z0fqdy70j3kz6aayetegur38gl&txType=TRANSFER&rows=25&page=1
vs
https://explorer.binance.org/api/v1/txs?address=bnb1pyzndgy0clkrehqke6h5jgrtdqzgdc78ac4qsr&page=1&rows=25

**Comment by EnoRage** [comment]
Maybe we will need to write open source rpc?)

**Comment by EnoRage** [comment]
https://dex.binance.org/api/v1/transactions?address=bnb1m7ly8xsty9rcfnhcdjnde4qtns27j0umpnv3ja

https://docs.binance.org/api-reference/dex-api/paths.html#apiv1transactions
max = 3 months

**Comment by kolya182** [comment]
> https://dex.binance.org/api/v1/transactions?address=bnb1m7ly8xsty9rcfnhcdjnde4qtns27j0umpnv3ja
> 
> https://docs.binance.org/api-reference/dex-api/paths.html#apiv1transactions
> max = 3 months

This then
https://dex.binance.org/api/v1/transactions?address=bnb1pyzndgy0clkrehqke6h5jgrtdqzgdc78ac4qsr&txType=TRANSFER&rows=25&page=1&endTime=1578168727000

**Comment by EnoRage** [comment]
Latest block
GetBlockByNumber
GetTokens of account
