### ISSUE TITLE
[Platform-API] Reverse name lookup

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/blockatlas#1018]
(Rationale) It would be nice to display human-friendly names instead of raw addresses in transaction history and other places in Trust Wallet.  For this, a reverse name lookup is needed (return name from raw address, if available).

To check: Which naming systems (ENS, unstoppable, FIO, ...) support reverse lookup (if any).

Solution:  
- New blockatlas API for reverse name lookup
- For naming systems with reverse lookup possibility, forward call and also use a cache.
- For naming systems with no reverse lookup possibility: maintain cache of name-address associations; return answer from the cache.  Update cache whenever a forward name lookup is performed (asynchronously).  Note that in case of cache miss there is no way to trigger search, so functionality will work only for addresses already seen by blockatlas; also results may be outdated (minor issue).

**Comment by EnoRage** [comment]
It is good idea just to add another field for "from", "to" addresses.
So it will be availible to return transactions like

"id": ..
"from": "0x...."
"from_domains":["vikmeup.eth," "viktor.eth", ...],
"to":"0x...",
"to_domains":["exchange.eth"],

**Comment by EnoRage** [comment]
The only issue is the perfomance. I don’t think that it is possible without caching to do that for transactions

**Comment by hewigovens** [comment]
I'm going to implement ENS/FIO reverse lookup, so it's easier for app to show name associated with their address or public key

**Comment by vikmeup** [comment]
Let's close this for now, not needed atm
