### ISSUE TITLE
[Platform-API] Remove CustomAPI for ETH and BTC

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1019]
Currently we use Custom API to register routes for ETH and BTC inside platform implementation. 
We need to find a better solution:

A. Try to use TransactionAPI and TokenAPI, TokenTxAPI for ETH and rewrite it to be compatible for this. Also do the same for BTC-like coins. Add New UTXO API specially for BTC-like coins and remove routes from BTC platform implementation

B. Any other option

Why current solution is bad:
1. Platform api must not depends on any http api implementation, it is a separate service that needs to be executed in any form
2. We need to have a consistent code, where it is really easy to understand where there are all the api route paths, we do not need to mix it with other services. Currently there is dependency like that
blockatlas.Platform -> api -> ethereum
But blockatlas.Platform use ethereum package

This is not critical issue, but it is important to use the best practices or at least not using worst of them

**Comment by catenocrypt** [comment]
CustomAPIs removed, routes optimized, PR #1068 .  I plan to continue, to change one route for a service, with coin being a parameter, instead of a route for each coin.
