### ISSUE TITLE
Add destinationTag to XRP

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#104]

**Comment by hewigovens** [comment]
XRP is done in this commit https://github.com/TrustWallet/blockatlas/commit/0de76c0aa9e5408910225f0e0da53966b4a6acd6
for Stellar / KIN, the memo field is in [transaction api](https://horizon.stellar.org/transactions/d47e3a9f1685020c182ee753ee92fe62ffe03c3f6aa951a20613b4de76e588c4), not [account api](https://horizon.stellar.org/accounts/GDMPB2GNHQTVHELX3RZMASMZG3ZH2MP2CKLFN7S7IV2CTTSOTMEXJI7S/payments?order=desc), it's worth to fetch each one to get the memo? @vikmeup

**Comment by vikmeup** [comment]
@hewigovens is there an API that would combine both? otherwise probably not worth it at this point

**Comment by hewigovens** [comment]
I didn't find it, or we can implement single tx api in blockatlas, app updates the tx when user views  tx detail (like nonce)?

**Comment by vikmeup** [comment]
@hewigovens it's ok as-is for now.

**Comment by vikmeup** [comment]
we would need memo in the future tho to send push notifications with a memo, but not critical atm.
