### ISSUE TITLE
Make list of bakers dynamic

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#1040]
## Current Functionality
Blockatlas gets list of bakers from Assets repo, at some point in time baker can run out of capacity to accept staking and users would continue delegate with out getting reward out. Some bakers come and [change](https://github.com/trustwallet/assets/pull/1930) their status, some don't. This is not sustainable and we need to find the way check capacity of each baker dynamically

## Possible Improvement
https://mainnet-tezos.giganode.io/chains/main/blocks/head/context/delegates/tz1V3yg82mcrPJbegqVCPn6bC8w1CSTRp3f8

**Comment by vikmeup** [comment]
This information is available from the rpc endpoint: `/chains/main/blocks/head/context/delegates/tz1V3yg82mcrPJbegqVCPn6bC8w1CSTRp3f8` 

From the team:
```
...GET ../<block_id>/context/delegates/<pkh>
Returns staking balances and whether deactivated or not
```

**Comment by EnoRage** [comment]
What is the status on it? @kolya182

**Comment by vikmeup** [comment]
@EnoRage This is completed?

**Comment by EnoRage** [comment]
Nope

**Comment by EnoRage** [comment]
#1153
