### ISSUE TITLE
[Platform-ETH] Add new type of metadata for ETH contract call 

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1041]
Currently there are some cases on contract call, when user
1. Send transaction to contract
2. Contract send some tokens to other user
3. Contract send some tokens to user back

It is important to understand that all users (addresses) who mentioned in this transaction will get be fetched by us properly (we will send them notifications and will show them tx history)

I suggest to create a new type of metadate for ETH contract call operations

Something with fields like:
```
from_contract_received: [ { "DAI", 10000, UserAddress, ...}, { "USDC", ...}, ... ]
from_contract_send_to: [ { "DAI", 10000, OtherUser1, ...}, { "USDC", OtherUser2 }, ... ]
```

It is just example with bad naming.

Currently tx direction for contract call for user A will be incoming if user receive some tokens back in this TX. It is not a good design and we will need to add additional logic to getTxDirection also

**Comment by EnoRage** [comment]
@hewigovens @prazd @catenocrypt  what do you think?

**Comment by hewigovens** [comment]
We already have a contract_call type, we might to extend it? When we have the data field we can do more, like swap type

**Comment by EnoRage** [comment]
It was closed by @hewigovens
