### ISSUE TITLE
[Token] Improve fetching tokens across different networks

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#1057]
## Summary of Bug

Currently fetching tokens for many networks (https://github.com/trustwallet/blockatlas/pull/1056) not very effective and computationally expensive, as 1 request generates fetch for over 10 different blockchains.

There is couple of things to improve: 

1) Split tokens fetch into separate micro service to avoid any bugs/crashes that could be caused
2) Provide caching mechanism to better handle getting tokens

## Steps to Reproduce

____

##### Request details:
```
{}
```

##### Response details:
```
{}
```

**Comment by EnoRage** [comment]
I suggest to create routing api service that will route all the requests to the necessary containers.

Example 1: /v1/ethereum will go to the eth container
Example 2: batch request for eth, bnb will be splited to the 2 requests for bnb and eth BUT anyone who will request it - will have 1 http request 

So, we will have all routing rules in code. Basically we will rewrite current ingress controller logic

**Comment by vikmeup** [comment]
Closing in favor of: https://github.com/trustwallet/blockatlas/issues/1172
