### ISSUE TITLE
Run naming, tokens, staking as independent services

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#1058]
## Summary

- [ ] naming
- [ ] tokens
- [ ] collectibles
- [ ] staking

**Comment by EnoRage** [comment]
Can you provide more details, please?

**Comment by vikmeup** [comment]
> Can you provide more details, please?

feel free to specify details for implementation. this is overall issue to split independent running services

**Comment by EnoRage** [comment]
> > Can you provide more details, please?
> 
> 
> 
> feel free to specify details for implementation. this is overall issue to split independent running services

Just cannot see any reason to split it

**Comment by EnoRage** [comment]
Got the details, will specify it soon

**Comment by EnoRage** [comment]
It is the same issue as https://github.com/trustwallet/blockatlas/issues/1057
Solution will be presented there as well
