### ISSUE TITLE
The latest release version (v1.1) is not semver compliant

### ISSUE THREAD

**Issue by yellowred** [trustwallet/blockatlas#1061]
When using blockatlas as dependency it is not possible to use the [latest release](https://github.com/trustwallet/blockatlas/releases/tag/v1.1) as it is not [semver compliant](https://semver.org/#spec-item-2). This makes it not being able to picked up by golang proxy:
```
➜  blockatlas git:(master) go list -m --versions
github.com/trustwallet/blockatlas v0.0.1 v0.0.2 v0.0.3 v0.0.4 v0.0.5 v0.0.6 v0.0.7 v0.0.8 v0.0.9 v0.0.10 v1.0.0 v1.0.1 v1.0.2 v1.0.4 v1.0.6 v1.0.7 v1.0.8 v1.0.9 v1.0.10 v1.0.11 v1.0.12 v1.0.13 v1.0.14 v1.0.15 v1.0.17 v1.0.18 v1.0.19 v1.0.20 v1.0.21 v1.0.22 v1.0.23 v1.0.24 v1.0.25 v1.0.26 v1.0.27 v1.0.28 v1.0.29 v1.0.30 v1.0.31 v1.0.32 v1.0.33 v1.0.37
```
Please tag the new version `v1.1.1`.

**Comment by kolya182** [comment]
https://github.com/trustwallet/blockatlas/releases/tag/v1.1.1
