### ISSUE TITLE
[Observer] Remove GUID field 

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1065]
I suggest to remove guid field for blockatlas subscriptions. There is no need at it. 
We suggest that client which will subscribe - will save information about person with that address. So, there is no need to store a specific guid for addresses. We can just use addresses instead.

**Comment by EnoRage** [comment]
@vikmeup @prazd what do you think about that?

**Comment by vikmeup** [comment]
guid help us identify association between entity <> address, maybe ok to keep as is for now?
