### ISSUE TITLE
Measure coverage of functional tests

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/blockatlas#1067]
Coverage is measured for the unit tests.  It would be nice to also measure the coverage for mocked functional tests.

**Comment by catenocrypt** [comment]
Unfortunately measuring coverage for externally-driven tests is not so straightforward.

A `main_test.go` can be added alongside cmd/platform_api/main.go, with a test to invoke main:

```
package main

import (
  "testing"
)

// Test started when the test binary is started. Only calls main.
func TestRunWithTest(t *testing.T) {
    main()
}
```

Then this can be executed as a test:
```
go test -cover -covermode=count -coverprofile=coverage.txt ./cmd/platform_api
```

Once executed, mocked tests has to be started, and then the platform binary stopped.
Or, it can be compiled and then executed:

```
go test -c -cover -covermode=count -coverprofile=coverage.txt -coverpkg=all -o bin/platform_api_cover ./cmd/platform_api
./bin/platform_api_cover -p 8437 -c configmock.yml -test.coverprofile=coverage.txt
```

However, I was not able to include all packages, only the 'main' package was included in the coverage, which is meaningless.
I played around with `-coverpkg=all` `-coverpkg=github.com/trustwallet/blockatlas/platform` with not much success.

(*Note:* one adjustment was needed in main/internal: argument parsing has to be split, glaf definition in init(), parsing in main.)

**Comment by EnoRage** [comment]
Cannot see any sense in it, let’s keep issues clean from tasks like this
