### ISSUE TITLE
Separate mock test output per mock file

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#1072]
Currently if mock fails, normally i search on https://dev.azure.com/TrustWallet/Trust%20BlockAtlas/_build/results?buildId=27101&view=logs&j=bd9bc89c-f7ed-5d00-2307-97661833a2b1&t=51c2314a-9229-56e3-1c98-f426bb34c6d2 `FAIL` or scroll to find where json did not match and it takes time

Proposal break down each mock file  test defined in `mock/ext-api-dyson/get or post` or any other solution that will help locate error faster and better indicate actual error.

@catenocrypt What do you think ?

**Comment by catenocrypt** [comment]
Let's focus on #927 , closing this.
