### ISSUE TITLE
Remove strange ports implementation from Makefile

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1082]
It is really weird implementation of mocked tests run at Makefile

I suppose not to check port by passing some strange empty json at postman/ directory

**Comment by EnoRage** [comment]
@catenocrypt can you take it on yourself, please

**Comment by catenocrypt** [comment]
Please explain in more detail what is wrong and/or propose alternative solution.

**Comment by EnoRage** [comment]
https://github.com/trustwallet/blockatlas/blob/master/tests/postman/mock-healthcheck_data.json

**Comment by EnoRage** [comment]
@catenocrypt what is this?

**Comment by EnoRage** [comment]
https://github.com/trustwallet/blockatlas/blob/master/Makefile#L138
Same question

**Comment by catenocrypt** [comment]
Closed via #1090 .
