### ISSUE TITLE
Consolidate client and parsing methods names which needs to be exposed

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#1088]
## Summary of Bug

https://github.com/trustwallet/blockatlas/pull/1087#discussion_r422691357
https://github.com/trustwallet/blockatlas/pull/1087#pullrequestreview-408776176
https://github.com/trustwallet/blockatlas/pull/1087#pullrequestreview-408776610

It needs to be normalized and have one standard for all platforms

**Comment by EnoRage** [comment]
Moved

**Comment by vikmeup** [comment]
> Moved

Where is being moved?
