### ISSUE TITLE
KIN empty amount during blocks parsing

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1106]
Sometimes getBlockByNumber parse txs with empty amount it breaks to UnmarshalJSON for blockatlas.Tx

**Comment by catenocrypt** [comment]
In platform/stellar/transaction.go there is explicit check for Amount != "", though error from DecimalToSatoshis is swallowed.  However, there is a bug in DecimalToSatoshis: leftmost 0s are trimmed, but if input is "0", result is "" (and no error).  In this case in normalized tx Value will be "".

**Comment by EnoRage** [comment]
👍🏻 great, just need to fix it

**Comment by catenocrypt** [comment]
DecimalToSatoshis is used by Cosmos and Solana.

**Comment by catenocrypt** [comment]
Should be solved, #1110 .
