### ISSUE TITLE
[Platform] Add Lending API, use Staking with Lending as Finance api

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1112]
We need to add Lending api (same as staking)

We currently needs to support Compound for lending.

Also there is some research about other lending providers that can be integrated.

**Comment by EnoRage** [comment]
It is still issue for open discussion, we need specification for clients and action flow for lending

**Comment by EnoRage** [comment]
@catenocrypt can you take it after  current issue? What do you think?

**Comment by EnoRage** [comment]
I suggest:

https://aave.com/

https://compound.finance/

https://iearn.finance/earn

https://idle.finance/#/dashboard/best

**Comment by catenocrypt** [comment]
Lending API prototype is being worked on here: #1116 .

**Comment by vikmeup** [comment]
Not relevant anymore
