### ISSUE TITLE
Support stake/unstake transaction for TRON

### ISSUE THREAD

**Issue by ArtemGoryunov** [trustwallet/blockatlas#1121]
## Current Functionality
List of transactions doesn't contain stake/unstake transaction. When a wallet imports those transactions doesn't appears in the wallet but It would be nice to have. 

## Possible Improvement
Return stake/unstake transaction

**Comment by kolya182** [comment]
Part of https://github.com/trustwallet/blockatlas/issues/1122

**Comment by EnoRage** [comment]
Duplicated
