### ISSUE TITLE
Naming providers should be more independent from platform structure

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/blockatlas#1125]
Naming providers (ENS, ZIL, FIO) are only a few, and not necessary closely part of the respective platform.  They should be more separated:
Naming provider instances are created separately from platforms (getNamingHandlers), so they should be also Init()ed separately.
Naming provider implementations should be taken out easily to create a service for naming lookups.

**Comment by EnoRage** [comment]
Duplicated
