### ISSUE TITLE
[KAVA/Cosmos] Rewrite Kava and Cosmos for the new api 

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#1142]
## Summary of Bug

Request: `/v2/kava/transactions/kava10gytfpmnffydm83at2hff3yuydnnzz2lghvely`

for transaction with hash: 
`BEAD62858E6C84F4EC65F57029DD9AC5D5CF7A869DA582407EA414C2CB8E8C0B` `metadata.value` should be more than 0, you can see details from the rpc node: `txs/BEAD62858E6C84F4EC65F57029DD9AC5D5CF7A869DA582407EA414C2CB8E8C0B`

**Comment by EnoRage** [comment]
It happened because of kava api changes. Currently it is not the same as for cosmos
