### ISSUE TITLE
[Platform] Binance(?) custom platform error

### ISSUE THREAD

**Issue by PAkhidue** [trustwallet/blockatlas#1144]
Hello everyone,

first of all thanks for this application. It works so far really well!
After a time, I noticed, the blockatlas API throws an error when requesting binance transactions:

![image](https://user-images.githubusercontent.com/45153452/84384146-d3f6ff00-abed-11ea-9981-025c1bad1512.png)

The thing is, it worked some days ago. (Server is running since 10 days~)
URL: http://localhost:8420/v1/binance/bnb14zc9p8wfmdkz0el0y79827w22jjf4ew0xznf89

I can't confirm, that it also happens with other platforms. In my config I used the platform "all".
Has anybody an idea where it could come from? Tried to figure it out, restarted the server, nothing changes.

After a pull and a complete reinstall it works again. I'm not sure if it will happen again in the next days.

Thanks for all the help and keep up the great application,
Pascal

**Comment by EnoRage** [comment]
It looks like you are reaching binance api requests limit

**Comment by PAkhidue** [comment]
@EnoRage Thanks. I guess that's it. Any idea how to setup the Binance API without throttling?
