### ISSUE TITLE
[Tezos] Migrate validators from assets

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1157]
https://github.com/trustwallet/assets/blob/master/script/gen_validators_tezos.ts rewrite to golang and use here

Upd: https://github.com/trustwallet/assets/blob/master/script/blockchain/tezos.ts

**Comment by hewigovens** [comment]
@vikmeup is this issue still valid?

**Comment by vikmeup** [comment]
Yes, logic should be migrated to blockatlas
