### ISSUE TITLE
Blockchain reorg handling

### ISSUE THREAD

**Issue by yellowred** [trustwallet/blockatlas#1158]
## Summary

Handle blockchain reorg and add/remove transactions that are added/gone.

## Problem Definition / Why?

There might be a case when a tip got changed and the new block has new transactions that are relevant to subscriptions and/or the transactions sent to notifier are gone. This means some of the relevant transactions will not be delivered with the current process and also some of the transactions might be erroneously reported to the wallet. This happens quite often on "fast" blockchains, like Ethereum.

## Proposal

Identify a reorg is very easy -- the app just needs to compare the latest block's hash with the one at the blockbook. If they do not match, then the block needs to be fetched and sent to the notifier again. This will cover one block reorg.

We can define a const BLOCK_REORG_DEPTH that will control the maximum depth of reorgs that the app would handle. If BLOCK_REORG_DEPTH=10 the app would need to store in the tracker table an array of hashes length of 10 where the hash[9] equals the last block in the blockchain and hash[0] would be block with height=latest-9. The app will be able to iterate backwards until it finds that the hashes match. All transactions from the updated blocks would have to be resent to the notifier again.

From blockbook docs:

> Note: Blockbook always follows the main chain of the backend it is attached to. If there is a rollback-reorg in the backend, Blockbook will also do rollback. When you ask for block by height, you will always get the main chain block. If you ask for block by hash, you may get the block from another fork but it is not guaranteed (backend may not keep it)

**Comment by EnoRage** [comment]
We use minConfirmation for block to handle it.
https://github.com/trustwallet/blockatlas/blob/master/coin/coins.yml#L93
