### ISSUE TITLE
Support multiple outputs in a transaction

### ISSUE THREAD

**Issue by yellowred** [trustwallet/blockatlas#1159]
## Summary

A transaction can have multiple relevant outputs that have subscriptions. Blockatlas currently derives addresses using fields From and To of a blockatlas.Tx: https://github.com/trustwallet/blockatlas/blob/master/services/observer/notifier/base.go#L34. Which means it will not notify subscriptions which addresses are in an output with index>0. 

## Problem Definition / Why?

Some customers use Copay wallet and send funds to multiple addresses.

## Proposal

In order for making it work blockatlas.Tx should return all addresses from all outputs in GetAddresses func.

**Comment by vikmeup** [comment]
This would be considered in the future to support multiple transaction types
