### ISSUE TITLE
[Bug] Fix ETH Collectibles status code

### ISSUE THREAD

**Issue by maxUo** [trustwallet/blockatlas#1176]
Problem: 
The user receives the wrong status code for a normal problem.
For example,
**GET** http://**_atlas_**/v3/ethereum/collections/**_some_**/collection/enjin

![image](https://user-images.githubusercontent.com/20925019/88569954-e31df900-d043-11ea-92d2-6bd28c3f2bea.png)

But in reality it should be 404 code.

**Comment by EnoRage** [comment]
@maxUo please provide specific example

**Comment by EnoRage** [comment]
@maxUo
