### ISSUE TITLE
[Delegations] Add staked balance in delegations response

### ISSUE THREAD

**Issue by leoneparise** [trustwallet/blockatlas#1180]
## Current Functionality
There are some coins that has auto-delegation (ALGO and VET), which the user delegates only by having a balance in their wallets. Take Algorand, for example:

```
https://blockatlas.trustwallet.com/v2/algorand/staking/delegations/3YE4CLWELB55PL6P4NYOA5U5LYYOOZ567WPSBWTBHCNROMUQTSC4KFDXTM
```

```json
{
    "delegations": [],
    "balance": "426761906",
    "address": "3YE4CLWELB55PL6P4NYOA5U5LYYOOZ567WPSBWTBHCNROMUQTSC4KFDXTM",
    "coin": {
        "coin": 283,
        "symbol": "ALGO",
        "name": "Algorand",
        "decimals": 6
    },
    "details": {
        "reward": {
            "annual": 6.1
        },
        "locktime": 0,
        "minimum_amount": "0",
        "type": "auto"
    }
}
```

To support those blockchains we should add a `staked` balance attribute. `staked` will be the **sum of current delegations** or **balance** for auto-delegated blockchains.

**Comment by ArtemGoryunov** [comment]
@EnoRage could you take this issue soon?

**Comment by vikmeup** [comment]
Closing this, clients would be responsible to fetch this data from the node itself
