### ISSUE TITLE
Potential collision and risk from indirect dependence "github.com/gotestyourself/gotestyourself"

### ISSUE THREAD

**Issue by KateGo520** [trustwallet/blockatlas#1186]
## Background
Repo `trustwallet/blockatlas` used the old path to import `gotestyourself` indirectly.
This caused that `github.com/gotestyourself/gotestyourself` and `gotest.tools` coexist in this repo：
https://github.com/trustwallet/blockatlas/blob/master/go.mod#L21 （Line 21 & 51）
```
github.com/gotestyourself/gotestyourself v2.2.0+incompatible // indirect
gotest.tools v2.2.0+incompatible // indirect 
```

That’s because the `gotestyourself` has already renamed it’s import path from "github.com/gotestyourself/gotestyourself" to "gotest.tools". When you use the old path "github.com/gotestyourself/gotestyourself" to import the `gotestyourself`, will reintroduces `gotestyourself` through the import statements "import gotest.tools" in the go source file of `gotestyourself`.

https://github.com/gotestyourself/gotest.tools/blob/v2.2.0/fs/example_test.go#L8 
```
package fs_test
import (
	…
	"gotest.tools/assert"
	"gotest.tools/assert/cmp"
	"gotest.tools/fs"
	"gotest.tools/golden"
)
```

"github.com/gotestyourself/gotestyourself" and "gotest.tools" are the same repos. This will work in isolation, bring about potential risks and problems. 

## Solution
1. Add replace statement in the go.mod file:
```
replace github.com/gotestyourself/gotestyourself => gotest.tools v2.2.0
```
Then clean the go.mod.

**Comment by KateGo520** [comment]
@EnoRage  @Pantani  Could you help me review this issue? Thx :p

**Comment by EnoRage** [comment]
| This will work in isolation, bring about potential risks and problems.

Cannot see any potential issue with it for now. It is indirect, so when other packages update it, we will remove it as well
