### ISSUE TITLE
[TRON] Look at transactions api

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1215]
/v2/tron/transactions/TRF6pgCye57T8GaCbxpTFiANY4gdTTCD7o?token=TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7

https://tronscan.org/#/transaction/7d7eb4dde7379efab223074cc746f272887ca4567a7d98e8d08e0ddbc76d338a

Show tx with 
7d7eb4dde7379efab223074cc746f272887ca4567a7d98e8d08e0ddbc76d338a

what is approve and have value -1

**Comment by hewigovens** [comment]
`approve` -1 basically means approve max amount
