### ISSUE TITLE
[Tokens] Tokens indexer

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#1234]
We need to add new worker to:
-  read all transactions from the queue (from parser)
-  parse all new assets and fetch info (name, symbol, decimal, coin like 714)
- save all new not existed before assets to db

It is perfect to fetch data like for each asset:
```
{
            "name": "Binance USD",
            "symbol": "BUSD",
            "type": "BEP2",
            "decimals": 8,
            "asset_id": "c714_BUSD-BD2"
}
```

Current database scheme for assets must be like that:

From:
```
ID uint
asset string
```

To:

```
ID uint
asset string
decimals uint
name string
symbol string
type reference to the other table with types (ERC20, BEP20, etc)
```

The first step is to do that for ETH only, secondly for TRON and BNB, BSC

**Comment by vikmeup** [comment]
Also include:
- createdAt field in the model
- expose rest api endpoint to fetch assets ordered by createdAt
