### ISSUE TITLE
Can I use this API with Python?  

### ISSUE THREAD

**Issue by EmmanuelTom** [trustwallet/blockatlas#1237]
I want to create a telegram bot that will send a message to a user via his telegram account if the user received Ethereum on his wallet.
The message include how much ETH received and the time received.
My language is python 

Can I archive that using this API with python?

**Comment by vikmeup** [comment]
no, this is Go Lang project

**Comment by EmmanuelTom** [comment]
> no, this is Go Lang project
OK, please do you know how I can archive that or where I can get the API?
