### ISSUE TITLE
Add ability to supply slips, addresses and webhook

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#128]
multi-coin wallets would want to register many wallets with different addresses

**Comment by terorie** [comment]
Subscribing to single addresses at once is already supported by `(Coin, Address) => Webhook`.
Is a bulk subscribe request needed?

**Comment by vikmeup** [comment]
yes, bulk is needed, let's assume I have 10 wallets, each wallet has ethereum, bnb and etc, I should be able to register them all for one user
