### ISSUE TITLE
ERROR: invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#1283]
## Summary of Bug

```
ERRO[0008] Failed to AddAssociationsForAddress: ERROR: invalid byte sequence for encoding "UTF8": 0x00 (SQLSTATE 22021)
```

This error is thrown in logs quite often

Related to UTF-8/string format

**Comment by hewigovens** [comment]
Is running ethereum parser enough to reproduce it?

**Comment by vikmeup** [comment]
> Is running ethereum parser enough to reproduce it?

Let me try to reproduce this, but it might be irrelevant after my code changes.

**Comment by vikmeup** [comment]
Resolved in: https://github.com/trustwallet/blockatlas/pull/1341
