### ISSUE TITLE
Add support for BSC collectibles

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#1313]
https://docs.bounce.finance/nft-issuance/nft-api-reference

**Comment by superzitao** [comment]
BEP-721:
Dego contract address: 0x4cde5683f5f5616a8919a1d487552f2454c47a33
holder address: 0xc523855c5f74af3b2876510727e82bf6e92e9f5e
https://nftview.bounce.finance/erc721?user_addr=0xc523855c5f74af3b2876510727e82bf6e92e9f5e&contract_addr=0x4cde5683f5f5616a8919a1d487552f2454c47a33&chain_id=56

BEP-1155:
Alpaca contract address: 0x060Dd632f7Dd45cb97A86376863D623d6756e848
holder address: 0xfeacd6424d484ce69e5d611e24adad70ded7e983
https://nftview.bounce.finance/assets/erc1155?limit=0&contract_addr=0x060Dd632f7Dd45cb97A86376863D623d6756e848&chain_id=56

> https://docs.bounce.finance/nft-issuance/nft-api-reference

**Comment by hewigovens** [comment]
this api is almost unusable, can't get any data from these two tokens
https://www.bakeryswap.org/#/my-new-artworks
https://pancakeswap.finance/nft

**Comment by hewigovens** [comment]
another way is to parse erc721 / erc1155 in blockaltas indexer
