### ISSUE TITLE
Simplify subscription model

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/blockatlas#1318]
remove address table and use notification_subscriptions table instead

**Comment by hewigovens** [comment]
will this also solve: https://github.com/trustwallet/blockatlas/issues/1283 ?

**Comment by vikmeup** [comment]
> will this also solve: #1283 ?

This is a separate issue, could be tackled after this issue is solved

**Comment by vikmeup** [comment]
Resolved: https://github.com/trustwallet/blockatlas/pull/1341
