### ISSUE TITLE
Create capability list

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#139]
All platforms not implemented equally, some only support token transfer others can support multi send etc.

[ ] - Create list of all supported platform and their capability
[ ] - Generate chart based on the list

```js
[
	{
		name: "Ethereum",
		pagination: false
		tokenTranfer: true,
	}
]
```

**Comment by artall64** [comment]
I see `Documentation` tag, is it means that feature already supported but just not yet documented ?

**Comment by artall64** [comment]
Related issues: 
https://github.com/trustwallet/blockatlas/issues/241
https://github.com/trustwallet/blockatlas/issues/141

**Comment by kolya182** [comment]
Swagger fixes this
