### ISSUE TITLE
trackers not init

### ISSUE THREAD

**Issue by prettyCoders** [trustwallet/blockatlas#1404]
![image](https://user-images.githubusercontent.com/36216120/106732732-00afc900-664c-11eb-8860-f3dac8838e43.png)

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/106737360-85e9ac80-6651-11eb-8a94-58400ee7bc01.png)
forever return

**Comment by hewigovens** [comment]
Please add a record to `trackers` table like this:

![image](https://user-images.githubusercontent.com/360470/106737932-a8cc8e80-665a-11eb-90dc-b5d1e3ec036d.png)

**Comment by prettyCoders** [comment]
All right!
