### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by robinsingh-bw** [trustwallet/blockatlas#141]
Would be nice if we can query transactions for an address by page number instead of just getting the first page all the time. Also, a 'total transactions' field would be desirable.

**Comment by kolya182** [comment]
@robinsingh-bw Noted, for which coin would like get pagination first ?

**Comment by artall64** [comment]
Seems this two is quite similar: 
https://github.com/trustwallet/blockatlas/issues/241

**Comment by artall64** [comment]
We might faced with some problems on ripple: https://github.com/ripple/rippled-historical-database/issues/198

**Comment by vikmeup** [comment]
Closing, as we don't have plans to support this at the moment
