### ISSUE TITLE
README has not been updated for a long time, can you update the latest README

### ISSUE THREAD

**Issue by songning4** [trustwallet/blockatlas#1429]
Some of the actions in the documentation have been changed

```
# Start notifier with the path to the config.yml ./ 
go build -o notifier-bin cmd/notifier/main.go && ./notifier-bin
```
It's like this operation has been abolished

**Comment by hewigovens** [comment]
will clean up a bit, you can check files under this folder https://github.com/trustwallet/blockatlas/tree/master/deployment

**Comment by songning4** [comment]
> will clean up a bit, you can check files under this folder https://github.com/trustwallet/blockatlas/tree/master/deployment

Thank you so much.

**Comment by songning4** [comment]
What is the relationship between setup, api, consumer, parser, please?

**Comment by songning4** [comment]
@hewigovens What is the relationship between setup, api, consumer, parser, please?

**Comment by Horlydan** [comment]
#870

**Comment by Horlydan** [comment]
#792
