### ISSUE TITLE
Fix Binance Client

### ISSUE THREAD

**Issue by terorie** [trustwallet/blockatlas#144]
https://explorer.binance.org APIs are to unstable and ceased to work for BlockAtlas.
Use Binance node client instead.

**Comment by kolya182** [comment]
Just to consider:
In terms of transactions history explorer api will return all transactions limited by `limit` param where any public Binance RPC link https://dex.binance.org/api/ only last 90 days as stated in docs https://docs.binance.org/api-reference/dex-api/paths.html#apiv1transactions + multisend transactions does't not supported.

https://dex.binance.org/api/v1/transactions?address=bnb1xwalxpaes9r0z0fqdy70j3kz6aayetegur38gl&limit=100 returned 5 trx vs

https://explorer.binance.org/api/v1/txs?address=bnb1xwalxpaes9r0z0fqdy70j3kz6aayetegur38gl&page=1&rows=100 returned 98 trx vs

@terorie
What exactly did you find to be unstable ?
Is any way you can query part of data from RPC and part from Explorer do spread the load and don't get rate limited on explorer api ?

**Comment by terorie** [comment]
@kolya182 The Binance DEX team doesn't promise any stability guarantees guarantees on the explorer API and might alter or remove those undocumented endpoints.
You are correct about the public DEX API, it isn't an option either.

We should run our own Binance chain node and use `apiserver` to provide a DEX API with full transaction history: https://docs.binance.org/api-reference/api-server.html#api-server
