### ISSUE TITLE
Return value in satoshi

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/blockatlas#145]
Add test to make sure `ALL` routes returned `value` in satoshis value 
https://blockatlas.trustwalletapp.com/v1/aion/a0d11a4790cc8b372242b19a1a1ff39dba964bc530e86f795294625383784929
`Actual`
```js
"value": "1022625548201000000.000000000000000000"
```

`Expected`:
```js
"value": "1022625548201000000"
```

**Comment by terorie** [comment]
Fixed in #135
