### ISSUE TITLE
Set GitHub description and tags

### ISSUE THREAD

**Issue by terorie** [TrustWallet/blockatlas#18]
The repository description is empty right now, and I don't have permissions to modify it.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/21371810/54651311-a71f6f00-4ab2-11e9-993e-7c5e7ab0df64.png">

How about `Clean and lightweight cross-chain transaction API. Backend of TrustWallet.`?

Tags: `crypto, blockchain, api, binance, trustwallet`

**Comment by vikmeup** [comment]
@terorie looks good to me!
