### ISSUE TITLE
[Observer] Add TRON support for BlockAPI

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#209]
curl -X POST  https://api.trongrid.io/wallet/getblockbynum -d '{"num":10874448}'

**Comment by kolya182** [comment]
From Tronscan api https://github.com/tronscan/tronscan-frontend/wiki/TRONSCAN-API#22

Get block info https://apilist.tronscan.org/api/block?number=5987471 use `timestamp to query transactions` https://apilist.tronscan.org/api/transaction?sort=-timestamp&count=true&limit=20&start=0&start_timestamp=1548056253000&end_timestamp=1548056253000 => 64 == 64 (https://tronscan.org/#/block/5987471)
