### ISSUE TITLE
Binance Integration Test: No transactions

### ISSUE THREAD

**Issue by terorie** [TrustWallet/blockatlas#23]
```
time="2019-03-23T13:03:13+01:00" level=info msg="Testing endpoint" @platform=binance
time="2019-03-23T13:03:14+01:00" level=warning msg="No transactions" @platform=binance
time="2019-03-23T13:03:14+01:00" level=info msg="Endpoint works" @platform=binance
time="2019-03-23T13:03:14+01:00" level=info msg="Endpoint tested" @platform=binance fields.time=592.104107ms
```

**Comment by terorie** [comment]
Binance DEX Index was reset, a new test address is needed.

**Comment by vikmeup** [comment]
https://binance-chain.github.io/api-reference/dex-api/paths.html#apiv1transactions

from the docs:
```
Query Window: Default query window is latest 24 hours; The maximum start - end query window is 3 months.
```

**Comment by terorie** [comment]
Another idea then: To keep the test generic, we define address getters per platform in the integration test.
Binance will just get a list of recent transactions and pick the first one.

**Comment by terorie** [comment]
The issue was in Binance's API. Fixed by switching to the explorer API.
