### ISSUE TITLE
[Ripple] Wrong transfer amount value returned

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#242]
https://xrpscan.com/tx/3D8512E02414EF5A6BC00281D945735E85DED9EF739B1DCA9EABE04D9EEC72C1
`Expected`: `0.0031 XRP`
`Actual`: `1000 XRP`

```json
{
            "id": "3D8512E02414EF5A6BC00281D945735E85DED9EF739B1DCA9EABE04D9EEC72C1",
            "coin": 144,
            "from": "raz97dHvnyBcnYTbXGYxhV8bGyr1aPrE5w",
            "to": "rna8qC8Y9uLd2vzYtSEa1AJcdD3896zQ9S",
            "fee": "120",
            "date": 1565114281,
            "block": 49163909,
            "status": "completed",
            "type": "transfer",
            "memo": "",
            "metadata": {
                "value": "1000000000",
                "symbol": "XRP",
                "decimals": 6
            }
        },
```

How to check:
http://localhost:8420/v1/ripple/rna8qC8Y9uLd2vzYtSEa1AJcdD3896zQ9S

**Comment by vikmeup** [comment]
It says `Amount: | 1,000 XRP` is it different transaction type? that we should ignore

**Comment by xrpscanner** [comment]
The transaction type is correctly identified as `Payment`. However, it is a partial payment as a result of trade ([partial payments](https://xrpl.org/partial-payments.html)). Your API backend must rely on `delivered_amount` property to calculate actual XRP amount delivered to the destination.
