### ISSUE TITLE
[Observer] Add Nebulas (NAS) support for BlockAPI

### ISSUE THREAD

**Issue by ArtemGoryunov** [trustwallet/blockatlas#249]
Documentation https://github.com/nebulasio/wiki/blob/master/rpc.md
There are the following methods:

```
LatestIrreversibleBlock
GetBlockByHash
GetBlockByHeight
```

**Comment by Lekky71** [comment]
Hi @ArtemGoryunov 
I have a few questions concerning the Nebula client.
1. There is an existing `GetTxs` function that calls the 'tx' endpoint but this endpoint is not in the documentation shared via the link above, is it not valid or there is another documentation?

2. When the Block response is gotten from the http request, which data is needed to be filtered out, 
Is it the entire response, or just the transactions list contained in it?

I look forward to your response, thank you.

**Comment by vikmeup** [comment]
@Lekky71 take a look at https://github.com/trustwallet/blockatlas/issues/268, I will be updating information on blockatlas usage, there is good examples.

**Comment by Lekky71** [comment]
Alright, thanks, I looked at the example PRs and saw that I have already done the same with the nebula platform, the only difference is that the methods are different (LatestIrreversibleBlock, GetBlockByHash, GetBlockByHeight), how do I hook them up with the observer?
