### ISSUE TITLE
Add support for collectibles

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#25]

**Comment by kolya182** [comment]
**Utilize OpenSea API**


**List of collections:** 
![IMG_5344](https://user-images.githubusercontent.com/3277207/60759938-d1555800-9fe1-11e9-8de0-cf1a2f1e4a54.PNG)


`/v1/collectibles/:address`
`/v1/collectibles/0x2614abecffaa3a938b8fbe0b1eaaa7a61e42f7a7`

List of items for the collectible:
![IMG_5345](https://user-images.githubusercontent.com/3277207/60759943-ddd9b080-9fe1-11e9-8225-467fb64bebcc.PNG)


`/v1/collectibles/:address/items/:contract`
`/v1/collectibles/0x2614abecffaa3a938b8fbe0b1eaaa7a61e42f7a7/items/0x2614abecffaa3a938b8fbe0b1eaaa7a61e42f7a7`
