### ISSUE TITLE
[Zilliqa] Error #01: json: cannot unmarshal object into Go value of type []zilliqa.Tx

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#252]
`Hot to test`
1. Set Zilliqa key in config_dev.yml
2. `go build -o blockatlas ./cmd && ./blockatlas api --config=config_dev.yml`
3. http://localhost:8420/v1/zilliqa/zil1t6rqdea62xzzjjasuhe7n2dk28hkqw56055eyc

**Comment by hewigovens** [comment]
This is caused by viewblock api which returns different json format

**Comment by hewigovens** [comment]
Fixed: https://blockatlas.trustwalletapp.com/v1/zilliqa/zil1t6rqdea62xzzjjasuhe7n2dk28hkqw56055eyc
