### ISSUE TITLE
endpoints list data is not correct

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/blockatlas#284]
## Summary of Bug

`endpoints` from https://blockatlas.trustwalletapp.com/v1/ is not correct

## Steps to Reproduce

visit https://blockatlas.trustwalletapp.com/v1/

```json
{
    "endpoints": ["/v2binance", "/v2waves"]
}
```

should be `/v2/binance`, `/v2/waves`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by vikmeup** [comment]
This is very nice, I did not we have config for this, so much easier to explore

**Comment by Pantani** [comment]
https://github.com/trustwallet/blockatlas/pull/287
