### ISSUE TITLE
[Bug] time="2019-09-01T00:40:07Z" level=error msg="Binance: Failed to decode error response" error=EOF

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#288]
## Summary of Bug

observer

## Steps to Reproduce

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Pantani** [comment]
#302
