### ISSUE TITLE
Return transactions list in the wrapper

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#29]
Instead of returning transactions as list, can we do, in which `docs` will contain transactions list and this should be used across blockatlas.

```json
{
    "docs": [{
    }],
    "status": true
}
```

in this case we can extend to support pagination and error handling easier

**Comment by kolya182** [comment]
Proposal for standardizing response object https://github.com/TrustWallet/blockatlas/issues/41
