### ISSUE TITLE
Request Standards to BlockAtlas

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/blockatlas#30]
This PR intend to establish minimum requirements to HTTP request. Please feel free to add a comment or suggestion. Once we finalize requirements requirements two PR must be made:

- [ ] Make appropriate changes to the code
- [ ] Update README file with finalized requirements

Each HTTP request to BlockAtlas (BA) and response from BA must contain next headers
`Accept: application/json`
`Accept-Encoding: gzip`

**Comment by terorie** [comment]
@kolya182 Is this applied to the requests to BlockAtlas, or the requests from BlockAtlas to chain HTTP APIs?

**Comment by kolya182** [comment]
@terorie Sorry for long response. Yes, this is requirements for incoming request and outgoing response to BlockAtlas (BA), i have updated it. As far as BA will communicate with multiple endpoints we ca handle that internally.
