### ISSUE TITLE
Waves Blockchain. The problem is getting all transactions.

### ISSUE THREAD

**Issue by krboktv** [trustwallet/blockatlas#347]
### The Waves blockchain is based on the NG Protocol. How it works: 
1. Creates an empty key block.
2. Every 3 seconds, the node pushes Microblocks until the key block is closed.

This link `https://nodes.wavesnodes.com/blocks/height` gives the height of the blocks since the generation of the last key block. Because of that some transactions will be lost.

**Comment by vikmeup** [comment]
Fixed in https://github.com/trustwallet/blockatlas/pull/351
