### ISSUE TITLE
No transaction for old transfers

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#370]
## Summary of Bug
We query last 100 transaction but actual TRANSFER could be behind the limit.

Possible to paginate over or use max timestamp available from rpc `v1/transactions?address=bnb1cwj0crr62qs67vzn6nhaqzza7dx754jkqkarxv&limit=100&txType=TRANSFER&endTime=1567875063000` docs (https://docs.binance.org/api-reference/dex-api/paths.html#apiv1transactions)

## Steps to Reproduce

v1/binance/bnb1cwj0crr62qs67vzn6nhaqzza7dx754jkqkarxv

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by EnoRage** [comment]
@kolya182 are solving that right now?

**Comment by kolya182** [comment]
> @kolya182 are solving that right now?

Planned for today

**Comment by kolya182** [comment]
Actually it was solved here https://github.com/trustwallet/blockatlas/commit/350d3e75af5eb456fe4878bb1b060391e15427ea
