### ISSUE TITLE
Replace end off life Veforge explorer

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#473]
https://www.reddit.com/r/CryptoCurrency/comments/dkigf4/veforge_announced_the_shutdown_of_their_block/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

https://medium.com/@vechainofficial/announcing-the-new-official-vechain-block-explorer-and-vechain-sync-ledger-wallet-interface-38a4b5360aeb

**Comment by vikmeup** [comment]
@kolya182 what's the status on this?

**Comment by kolya182** [comment]
Scheduled for this week

**Comment by Pantani** [comment]
https://github.com/trustwallet/blockatlas/pull/557
