### ISSUE TITLE
Theta support

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#49]
Docs: https://github.com/thetatoken/theta-mainnet-integration-guide/blob/master/docs/api.md#api-reference

Looking for the indexer

https://explorer.thetatoken.org:9000/api/accounttx/{address}?type=2&pageNumber=1&limitNumber=50&isEqualType=true

**Comment by vikmeup** [comment]
?token=tfuel - this parameter should only return fuel transactions

**Comment by kolya182** [comment]
Closed in https://github.com/TrustWallet/blockatlas/pull/106
