### ISSUE TITLE
Nano push notification support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/blockatlas#508]
might be tricky, since each account is a blockchain

**Comment by catenocrypt** [comment]
I think true push notification is only possible when we run our own node.
Nano node has an RPC callback feature, whereby it sends a notification about every new confirmed block in the network.  RPC callback is controlled through configuration (by the one running the node), not through API.
As every account is a separate chain in nano, there is no single blockheight, it is not possible to poll for all new blocks, accounts can be created at any time.

Alternatives:
1. Own node, delivers RPC callback of all nodes to backend, backend filters to relevant accounts, notifies clients.
2. Backend frequently polls all relevant accounts of all clients (using remote node) -- impractical
3. Clients poll for their account(s) at specific timepoints -- no push notification

RPC callback doc:   https://docs.nano.org/integration-guides/advanced/#http-callback

**Comment by vikmeup** [comment]
@catenocrypt thank you for providing detailed explanation on this. 

I would propose to postpone implementation for this feature until we have higher demand for Nano push notifications.

Let's re-open this later.
