### ISSUE TITLE
[Platform] Replace go-ethereum with lightweight alternative

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/blockatlas#512]

**Comment by Pantani** [comment]
@hewigovens the ENS package uses the Go-Ethereum package as well. If we remove from Blockatlas, we need to download the lib as well, and the Geth going to be inside the `go.mod` as `// indirect`

We need need to change the ENS library as well, is this viable?

**Comment by hewigovens** [comment]
I think we may have to re implement go-ens by ourselves to support better batch query.
The only dependency might be go ethereum abi
