### ISSUE TITLE
Integration tests for naming service

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/blockatlas#541]
test .eth/.zil, and .crypto in the future

**Comment by hewigovens** [comment]
what's the status of this issue?

**Comment by EnoRage** [comment]
@vikmeup please, provide information about it. Maybe open another issue for it and close that?

**Comment by vikmeup** [comment]
We need to test endpoint and it's result (JSON response):

Example:
Request: https://blockatlas.trustwalletapp.com/ns/lookup?coin=60&name=vikmeup.eth
Response: 
```
{
   "result":"0x84E79D544B4b13bC3560069cfD56A9D5bbE7521d",
   "coin":60
}
```
