### ISSUE TITLE
Tron return extra transactions

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#591]
`/v2/tron/transactions/TN6qByCagkmUXxAwj1MeNfvRiLHtiXcPv6`

https://tronscan.org/#/address/TN6qByCagkmUXxAwj1MeNfvRiLHtiXcPv6

![IMAGE 2019-11-27 23:02:44](https://user-images.githubusercontent.com/1641795/69784163-05d0d880-116a-11ea-86ec-39091a12c58b.jpg)

**Comment by kolya182** [comment]
Fixed in https://github.com/trustwallet/blockatlas/commit/c346b9f64b8a708ee5ef4bb8e4b2bee33a5ffe44 and https://github.com/trustwallet/blockatlas/commit/bf65652857d6094826f47275e17116215a867a9c
