### ISSUE TITLE
Add Harmony platform

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#614]

**Comment by vikmeup** [comment]
@lorenzozanotto, this will help https://developer.trustwallet.com/blockatlas/newblockchain

**Comment by lorenzozanotto** [comment]
@vikmeup code and tests written, I'm waiting for the Harmony team to unlock the task by providing support on why transactions don't show up using their RPC methods. In the meanwhile I'm going to create a pull request so the code that's been written can be visible. This will allow us to push one button to send the code through the pipeline when Harmony team will solve the matter
