### ISSUE TITLE
Improve collectibles parsing

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#643]
1) https://api.opensea.io/collections/?asset_owner=0x84e79d544b4b13bc3560069cfd56a9d5bbe7521d, use `slug` instead of `primary_asset_contracts`
2) https://api.opensea.io/collections/?asset_owner=0x84e79d544b4b13bc3560069cfd56a9d5bbe7521d, from comment: it looks like you're using the contract's description there instead of the collection's description. we can't change the Enjin contract description to that. but the collection description already says that here in the API data: https://api.opensea.io/collections/?asset_owner=0x84e79d544b4b13bc3560069cfd56a9d5bbe7521d

**Comment by Pantani** [comment]
@dpereskokov we need to update the slug query as well before to close this issue
