### ISSUE TITLE
Tron support

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#65]
`/tron`

@kolya182 can you provide endpoints from the official docs? and trongrid endpoint? it's ok if it's not working yet

**Comment by kolya182** [comment]
https://developers.tron.network/docs/new-api-service
https://developers.tron.network/docs/trongridjs

**Comment by terorie** [comment]
```
Thank you for being an early adopter of the new TronGrid API service! In this Alpha phase, there are 5 new APIs available for testing. Currently, an experimental code is required for using the service. If you are interested in trying out the new APIs but do not have the code, please email our product manager Yue Fang.
```

@vikmeup Can you please contact him and ask for a code? yue.fang@tron.network

**Comment by kolya182** [comment]
> > Thank you for being an early adopter of the new TronGrid API service! In this Alpha phase,
> > there are 5 new APIs available for testing. Currently, an experimental code is required for using the service. If you are interested in trying out the new APIs but do not have the code, please email our product manager Yue Fang.
> 
> @vikmeup Can you please contact him and ask for a code? [yue.fang@tron.network](mailto:yue.fang@tron.network)
This are new endpoints https://github.com/TrustWallet/blockatlas/issues/65#issuecomment-483300968
