### ISSUE TITLE
Move init function for platforms one level higher 

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#668]
## Summary of Bug

https://github.com/trustwallet/blockatlas/pull/659/files#diff-065221b9b316144f63088daf71d6fcd2R20

Currently each platform is aware of `viper` and it reads values inside each value - we should move that logic out to registry, so that registry will pass url that platform needs to work with.

Ideally we register and specify params here: https://github.com/trustwallet/blockatlas/blob/master/platform/registry.go#L36, tricky part is - viper is not active as this point, so we need to find a good solution

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Pantani** [comment]
@EnoRage you can close this one

#887

**Comment by EnoRage** [comment]
Will be merged to master soon, currently is at dev branch

**Comment by EnoRage** [comment]
Closed by @Pantani  #887
