### ISSUE TITLE
[Tezos] Transactions not being returned for staking rewards

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#681]
https://tezos.id/operations/oomQk3tbby2xeKFHXhTD72BLsrBs67yTGEhVpkhF9gAhtjxMBMd

I have missing transaction for this address: tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK

**Comment by Pantani** [comment]
@vikmeup the current API doesn't return this transaction:
https://api.tzstats.com/explorer/account/tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK/op?limit=1000&offset=0

we can change to this API, but it returns a max of 50 transactions:
https://api.tezos.id/mooncake/mainnet/v1/transactions?account=tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK&n=50

**Comment by vikmeup** [comment]
if tezos.id solves the issue, let's use them, just make sure it's a reliable service
