### ISSUE TITLE
[Terra] Question for implementing chain with multiple coins

### ISSUE THREAD

**Issue by YunSuk-Yeo** [trustwallet/blockatlas#693]
## How can we help ?

In Terra blockchain, we have multiple stable coins including LUNA. Terra allows sending multiple coins  in a transaction like "100 LUNA, 1000 KRT" and also can pay fees with multiple coins. However current blockatlas interface seems allow only single coin to pay fee and single coin to be sent.

shortly I want to check, 
Can we return below formatted Tx as a response of `Client.GetTxsOfAddress()`? 
```
var transferDst = blockatlas.Tx{
	ID:     "06011507E4F3EF150C92F2DDB217499F2020801B7323C9C3ADDE1138916B0F98",
	Coin:   coin.LUNA,
	From:   "terra1rf9xakxf97a49qa5svsf7yypjswzkutqfclur8",
	To:     "terra1t849fxw7e8ney35mxemh4h3ayea4zf77dslwna",
	Fee:    "0.001177 KRT",
	Date:   1576555436,
	Block:  45478,
	Status: blockatlas.StatusCompleted,
	Type:   blockatlas.TxTransfer,
	Meta: blockatlas.Transfer{
		Value:    "480000.000000 KRT, 1771.645906 LUNA",
		Symbol:   coin.Terra().Symbol,
		Decimals: 6,
	},
}
```

If this type of method is not allowed, what is best practice to support it?

**Comment by vikmeup** [comment]
One option would be to extend transaction formats: `https://developer.trustwallet.com/blockatlas/transaction-format#native-token-transfer` to include multi transfers action/event

**Comment by YunSuk-Yeo** [comment]
@vikmeup Which channel can we use to get your intention to include Terra?

**Comment by Pantani** [comment]
@YunSuk-Yeo look the Binance platform implementation for multiple addresses/assets tx
https://github.com/trustwallet/blockatlas/tree/master/platform/binance/api.go#L102

You can follow these steps to add a new coin 
https://developer.trustwallet.com/blockatlas/newblockchain
