### ISSUE TITLE
Split implementation of the protocol into separate files

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#715]
## Summary of Bug

Currently all implementation for blockchain platform contain all protocol implementation, very hard to navigate and support

Tron has a good example of the structure (https://github.com/trustwallet/blockatlas/tree/master/platform/tron)

```
api.go
api_test.go
client.go
model.go
stake.go
stake_test.go
```

But this could be improve to have `block.go`, `transactions.go` and etc

- [x] Update https://developer.trustwallet.com/blockatlas/newblockchain

**Comment by vikmeup** [comment]
Any reasons to close this issue?

**Comment by Pantani** [comment]
sorry, I forget to link the PR

https://github.com/trustwallet/blockatlas/pull/802

**Comment by vikmeup** [comment]
It was not just stake related problem, it's overall problem to define proper structure for all the files, transactions, block parsing, and etc

**Comment by Pantani** [comment]
> But this could be improve to have block.go, transactions.go and etc

The most of coins use the same models and the normalize for block and transaction API, I don't think is a good idea to split these APIs, which can be more confused. My suggestion is split only no related things, like the ZNS lookup

**Comment by vikmeup** [comment]
Can you define proper files structure for platforms and other services and let's have one guide for having correct file structure

**Comment by Pantani** [comment]
yes, I going to update all docs today
