### ISSUE TITLE
APR of Tron and Cosmos Staking needs to be updated

### ISSUE THREAD

**Issue by zachzwei** [trustwallet/blockatlas#725]
## Summary of Bug

Tron Staking APR shows as 0.74% in the app. The current staking reward on Binance.com is 6.7646%
Cosmos Staking shows 11% but no validator has this APR showing. Please double check and correct the percentage.

Staking Rewards on Binance.com
![image](https://user-images.githubusercontent.com/35627271/72660469-80e79a00-3a09-11ea-8806-4ca0cf9e8f7c.png)

Staking Rewards within in the app
![image](https://user-images.githubusercontent.com/35627271/72660479-ad031b00-3a09-11ea-908f-c0e3ae24a88e.png)

![image](https://user-images.githubusercontent.com/35627271/72947043-bb5f8700-3dbb-11ea-8c73-f00851742a75.png)

## Steps to Reproduce

Checked Android 1.7.151, Tron Staking APR is also 0.74%

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by EnoRage** [comment]
Currently, Cosmos APR is hardcoded [here](https://github.com/trustwallet/blockatlas/blob/master/platform/cosmos/stake.go#L43)
Tron APR is hardcoded [here](https://github.com/trustwallet/blockatlas/blob/master/platform/tron/api.go#L17) as well.

**Comment by Pantani** [comment]
we need to find a way to have this dynamically. 

The same for Tezos:
https://github.com/trustwallet/blockatlas/tree/master/platform/tezos/api.go#L130

duplicated issue:
https://github.com/trustwallet/blockatlas/issues/455

**Comment by EnoRage** [comment]
The main points, for now, that were discussed with @vikmeup:
- Add cache for Platform (there are multiple suitable methods)
- Use @vikmeup Cosmos pull request for it, do the same for Kava
- TRON, TEZOS and other blockchains will have dynamic APR later, currently, it is not critical
- #455 needs to be modified and contain all blockchains that need  dynamic APR

I will use https://github.com/trustwallet/blockatlas/pull/669 request to:
- [ ] Add dynamic APR for Cosmos and Kava
- [ ] Add caching to Platform service for ( APR, GetDetails(), potentially some other methods)

@Pantani, @vikmeup, please, confirm

**Comment by vikmeup** [comment]
👍

**Comment by EnoRage** [comment]
- [x] Add dynamic APR for Cosmos and Kava
- [x] Add caching to Platform service for ( APR, GetDetails(), potentially some other methods)

**Comment by EnoRage** [comment]
Can be closed

**Comment by zachzwei** [comment]
Can you review this again as the APR shown on the app is lower compared to what our users are earning.
https://twitter.com/Ahmad_Usman1/status/1248256019769118720

**Comment by EnoRage** [comment]
> Can you review this again as the APR shown on the app is lower compared to what our users are earning.
> https://twitter.com/Ahmad_Usman1/status/1248256019769118720
Can you please create a new issue for that?

**Comment by zachzwei** [comment]
Done https://github.com/trustwallet/backend/issues/602
