### ISSUE TITLE
[Platform] Add Vechain and Ontology to Staking List API

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#727]
Just return APR, nothing else is required

**Comment by Pantani** [comment]
it's hard to get this APR dynamics, maybe we need to think a way to calculate that to all stake coins or try to get from a 3rd party API

**Comment by kolya182** [comment]
> it's hard to get this APR dynamics, maybe we need to think a way to calculate that to all stake coins or try to get from a 3rd party API

For VeChain calculation is hard, require store offline data and calculate, try use static for now https://vechainstats.com/vtho-calculator/  . Notice APR changes based on holding period (see calculator output)
Fox ONT: https://www.stakingrewards.com/asset/ontology

**Comment by Pantani** [comment]
> > it's hard to get this APR dynamics, maybe we need to think a way to calculate that to all stake coins or try to get from a 3rd party API
> 
> For VeChain calculation is hard, require store offline data and calculate, try use static for now https://vechainstats.com/vtho-calculator/ . Notice APR changes based on holding period (see calculator output)
> Fox ONT: https://www.stakingrewards.com/asset/ontology

Yes, I don't see a way to calculate that without a given balance

**Comment by vikmeup** [comment]
Closing for now, we can re-open later
