### ISSUE TITLE
[Charts] Data not available for BUSD

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#741]
## Summary of Bug

Coin listed on CMC: https://coinmarketcap.com/currencies/binance-usd/, but not available via charts api

URL: `http://localhost:8420/v1/market/info?coin=714&currency=USD&token=BUSD-BD1`

Response:
```
{"code":500,"error":{"error":"No chart coin info data found","meta":{"coin":714,"token":"BUSD-BD1"}}}
```

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Pantani** [comment]
fixed
https://github.com/trustwallet/assets/pull/1118
