### ISSUE TITLE
[Code style] Uber Go code style Guide 

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#745]
I want to ask everyone that is contributing to that project. Is it ok for you to agree using [Uber code style guide](https://github.com/uber-go/guide)?
 
If it is everyone is ok with it then I can suggest refactoring namings, imports, variable declarations, and some package usages as well as other non-mentioned stuff asap. I think that it can significantly improve the contribution quality

**Comment by Pantani** [comment]
Going to be awesome, but I think we should try to use that in the new development codes to see if the team going to adapt, and we can do the refactor after we solve the most significant issues from the repo.
