### ISSUE TITLE
Support BNB transfer with multiple addresses

### ISSUE THREAD

**Issue by Pantani** [trustwallet/blockatlas#754]
## Summary of Bug

Support BNB transfer with multiple addresses

## Expected Behavior

the transaction [`0C954A46D5AE90EBF9CB7E6F2EAC0E7C3E8DA2DA94B868962164A3AF9D54BEE8`](https://explorer.binance.org/tx/0C954A46D5AE90EBF9CB7E6F2EAC0E7C3E8DA2DA94B868962164A3AF9D54BEE8) need to be inside the transaction history:

`http://localhost:8420/v1/binance/bnb1nm4n03x00gw0x6v784jzryyp6wxnjaxswr3xm8`

## Current Behavior

The transaction is missing

## Steps to Reproduce

`http://localhost:8420/v1/binance/bnb1nm4n03x00gw0x6v784jzryyp6wxnjaxswr3xm8`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by catenocrypt** [comment]
Additional info:

This tx shows up in the txs result with "hasChildren":1, but no details on the sub-txs
```
{"txHash":"0C954A46D5AE90EBF9CB7E6F2EAC0E7C3E8DA2DA94B868962164A3AF9D54BEE8","blockHeight":64374278,"txType":"TRANSFER","timeStamp":1580128370826,"txFee":0.00060000,"txAge":16797,"code":0,"log":"Msg 0: ","confirmBlocks":0,"memo":"","source":0,"hasChildren":1}
```

A separate _tx_ call shows the details:

``` 
curl https://explorer.binance.org/api/v1/tx?txHash=0C954A46D5AE90EBF9CB7E6F2EAC0E7C3E8DA2DA94B868962164A3AF9D54BEE8
```

```
{"txHash":"0C954A46D5AE90EBF9CB7E6F2EAC0E7C3E8DA2DA94B868962164A3AF9D54BEE8","blockHeight":64374278,"txType":"TRANSFER","timeStamp":1580128370826,"txFee":0.00060000,"txAge":18651,"code":0,"log":"Msg 0: ","confirmBlocks":46635,"memo":"","source":0,"sequence":154231,"hasChildren":1,"subTxsDto":{"totalNum":2,"pageSize":15,"subTxDtoList":[{"hash":"0C954A46D5AE90EBF9CB7E6F2EAC0E7C3E8DA2DA94B868962164A3AF9D54BEE8","height":64374278,"type":"TRANSFER","value":3269.00000000,"asset":"AERGO-46B","fromAddr":"bnb1nm4n03x00gw0x6v784jzryyp6wxnjaxswr3xm8","toAddr":"bnb1eff4hzx4lfsun3px5walchdy4vek4n0njcdzyn","fee":0.00060000},{"hash":"0C954A46D5AE90EBF9CB7E6F2EAC0E7C3E8DA2DA94B868962164A3AF9D54BEE8","height":64374278,"type":"TRANSFER","value":1.00000000,"asset":"BNB","fromAddr":"bnb1nm4n03x00gw0x6v784jzryyp6wxnjaxswr3xm8","toAddr":"bnb1eff4hzx4lfsun3px5walchdy4vek4n0njcdzyn","fee":null}]}}
```
