### ISSUE TITLE
[Domains] Add support to FIO protocol

### ISSUE THREAD

**Issue by Pantani** [trustwallet/blockatlas#760]
## Summary

Add support to FIO protocol

## Problem Definition / Why?

We need to integrate domains lookup for FIO protocol

## Where/how shows?

When we send a transaction to another user

## Proposal

Implement a naming service API
https://github.com/trustwallet/blockatlas/blob/master/pkg/blockatlas/api.go#L75

https://github.com/trustwallet/blockatlas/blob/master/api/naming_service.go

**Comment by catenocrypt** [comment]
Solved with PR #780 .
