### ISSUE TITLE
Create Ontology normalizeBlockTransaction method

### ISSUE THREAD

**Issue by Pantani** [trustwallet/blockatlas#763]
## Summary of Bug

The method `normalizeBlockTransaction` method is missing:
https://github.com/trustwallet/blockatlas/blob/master/platform/ontology/api.go#L85

## Expected Behavior

You should split the parser from the API method and create a `normalizeBlockTransaction` method and your respective unit test

**Comment by Pantani** [comment]
@EnoRage

**Comment by EnoRage** [comment]
Will be soon

**Comment by EnoRage** [comment]
We can close #756 issue I think
