### ISSUE TITLE
[Markets] Something strange happening with /market/info

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#765]
Details:
Look at total supply
![Screen Recording 2020-01-28 at 14 14 40](https://user-images.githubusercontent.com/22479658/73260030-1e955300-41da-11ea-94da-d5809827d957.gif)
Steps to reproduce:

- Run blockatlas with api + sync markets
- Go to POSTMAN 
- QUERY: http://localhost:8420/v1/market/info?coin=60&time_start=1574483028&currency=USD
- Look at response body

**Comment by Pantani** [comment]
@EnoRage, probably the problem is here
https://github.com/trustwallet/blockatlas/tree/master/syncmarkets/charts.go#L53

If do you try to request a lot of times from the same provider, starts to return an error and the app gets the value from the next provider
