### ISSUE TITLE
[CI/CD] Unit test Test_normalizeCharts strange random behavior

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#766]
Several times this test is failing randomly.

<img width="1051" alt="Screen Shot 2020-01-28 at 14 27 20" src="https://user-images.githubusercontent.com/22479658/73260119-4d132e00-41da-11ea-98c8-31cb6781510d.png">

I suppose that we need to look at https://github.com/trustwallet/blockatlas/blob/master/marketdata/chart/coinmarketcap/cmc.go#L81 
Normalization

**Comment by Pantani** [comment]
your branch is updated? I did fix that 3 days ago. If the problem persists, we need to sort the array before the assert them

https://github.com/trustwallet/blockatlas/commit/441bf439ee8cd0b1df355f0944ff75b13eceade5
