### ISSUE TITLE
TRON: wrong address, timestamp, and missing block returned

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/blockatlas#77]
https://blockatlas.trustwalletapp.com/v1/tron/TKLnCNY5EsLNCvCXQTCn1dtqvc6vHhJUyJ

TODO:
- [x] Fix timestamp: 1555802447872 / 1000
- [x] Missing `block` property in response
- [x] `from` and `to` must be Tron address, not hex
- [x] Add test covers check for mentioned issues above

**Comment by terorie** [comment]
@kolya182 The Tron response doesn't return the block height

**Comment by kolya182** [comment]
> @kolya182 The Tron response doesn't return the block height

Use default block as `0`, client actually don't need it. But make a note for future fix, to keep api consistent.

**Comment by terorie** [comment]
```go
// Height of the block the transaction was included in
Block uint64 `json:"block,omitempty"`
```

I deliberately made the `block` parameter optional because I felt not including it when unknown is more correct than setting it to some value. Same thing with the `sequence` field.

But no more `omitempty`, noted. Let's specify `0` as the value for unknown height then.

**Comment by vikmeup** [comment]
@terorie that looks good! if omitted, iOS/Android client will default to 0

@madcake
