### ISSUE TITLE
[Tests] Write tests for EACH api method  

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#783]
Currently integration tests have no sense, it is easily possible to add / change something and pass all the tests successfully.

We need to have integration tests for EACH api method

**Comment by EnoRage** [comment]
Final solution:

Use jmeter for integration tests with mockups of external API responses
Use postman collections tests for testing with production endpoints

**Comment by kolya182** [comment]
> Final solution:
> 
> Use jmeter for integration tests with mockups of external API responses
> Use postman collections tests for testing with production endpoints

Currently i have all endpoint query in Postman, but no test. If you can provide frame work for test i can move them from current solution.

**Comment by arein** [comment]
New to the project and nitpicking a little bit :-)
we have functional tests - wouldn't we call it a functional test when we mock out external API responses?
We should scope out a long-term solution for integration testing other than Postman collections.

**Comment by catenocrypt** [comment]
There are many types of tests w.r.t. scope of components included and entry point levels, and different projects call them with different names.  There is no right or wrong, but within a project there should be an agreement on the naming.
In my view there are 3 important test classes:
1. test a smaller part of the project in isolation
2. test several smaller parts of the project, but without external dependencies (with mocks)
3. test (parts of) the project together with external components/services.

How do we call these tests in blockatlas?

My preference is _unit_; _integration_; _system_, but I'm fine with other names as well.  Oh, and these are all functional tests.

**Comment by catenocrypt** [comment]
> Final solution:
> 
> Use jmeter for integration tests with mockups of external API responses
> Use postman collections tests for testing with production endpoints

What are the arguments for jmeter?

**Comment by arein** [comment]
@catenocrypt few thoughts.

1. You propose _unit test_ here: agreed - just wanted to add that you probably want to mock out dependencies here as well
2. i think there's a step before _integration tests_ that blockatlas already implements: functional tests - mock out service dependencies e.g. node responses but call the system the way your customers would call you. in this case for instance make HTTP requests
3. integration tests: I am used to running integration tests _with_ external dependencies aka no mocks
4. system tests: not familiar with the naming - I've seen _end 2 end test_ being used commonly for a test involving multiple systems e.g. a test involving all components of blockatlas: markets, platform, and observer

**Comment by Pantani** [comment]
Now we have tests for all API's:

To run Postman Newman test, the host parameter is required, and you can specify the name of the test do you wanna run (transaction, token, staking, collection, domain, healthcheck, observer). 

E.g:
`$ make newman host=http://localhost:8420`
`$ make newman test=staking host=http://localhost:8420`

https://github.com/trustwallet/blockatlas/pull/831

**Comment by catenocrypt** [comment]
See also:  https://github.com/trustwallet/blockatlas/pull/886
