### ISSUE TITLE
[Markets] USD for rates is not available with clean Redis

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#784]
try to POST:
http://localhost:8420/v1/market/ticker
with
```json
{
    "coin": 60,
    "type": "token",
    "token_id": "0x0f7F961648aE6Db43C75663aC7E5414Eb79b5704"
}
```
you will get 
```json
{
    "code": 500,
    "error": "Invalid currency"
}
```

On the production you will not got the 500 only because Redis is there for ages.
If you will try the same with the previous commits before my small refactoring - you will got the same issue

**Comment by Pantani** [comment]
@EnoRage sorry, I don't understand the point, what's the expected behavior? If the Redis is clean, we don't have data to lookup

**Comment by EnoRage** [comment]
It is a bug
Currently Market Rates will no set to USD to the Redis

**Comment by kolya182** [comment]
> It is a bug
> Currently, Market Rates will not set USD data to the Redis

Maybe not related, but for me issues was missing api key in config for Fixer. Maybe need at check and log issue for better troubleshooting.

**Comment by Pantani** [comment]
Do you need a paid account from Fixer

**Comment by kolya182** [comment]
> Do you need a paid account from Fixer

NO https://fixer.io/product

**Comment by kolya182** [comment]
Is this is not an issue with provided solution, then close it
