### ISSUE TITLE
Better display error when market-sync kicks in. Prettify output

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#819]
<img width="1188" alt="Screen Shot 2020-02-07 at 11 26 15 AM" src="https://user-images.githubusercontent.com/3277207/74059320-a7f81280-499c-11ea-92ef-9513c58998ab.png">
<img width="2524" alt="Screen Shot 2020-02-07 at 11 26 21 AM" src="https://user-images.githubusercontent.com/3277207/74059328-ab8b9980-499c-11ea-8f42-713f51402b74.png">
<img width="2560" alt="Screen Shot 2020-02-07 at 11 26 41 AM" src="https://user-images.githubusercontent.com/3277207/74059352-b6dec500-499c-11ea-8060-635968986ef3.png">

**Comment by EnoRage** [comment]
https://github.com/trustwallet/blockatlas/issues/752

**Comment by EnoRage** [comment]
Migrated to watchmarket
https://github.com/trustwallet/watchmarket/issues/4
