### ISSUE TITLE
Stellar transactions seem not synced with the latest state

### ISSUE THREAD

**Issue by eddywm** [TrustWallet/blockatlas#82]
https://blockatlas.trustwalletapp.com/v1/stellar/GCILJZQ3CKBKBUJWW4TAM6Q37LJA5MQX6GMSFSQN75BPLWIZ33OPRG52

https://stellarscan.io/account/GCILJZQ3CKBKBUJWW4TAM6Q37LJA5MQX6GMSFSQN75BPLWIZ33OPRG52

Looks like the BlockAtlas Stellar endpoint is not synced to latest transactions state. 
It's not bringing newer transactions

**Comment by kolya182** [comment]
@eddywm I have checked, and could not find any missing transactions. Currently we only support one type of transactions is `payments` https://stellar.expert/explorer/public/tx/100073493911146496#100073493911146497
