### ISSUE TITLE
Improve handling for inactivate, outdated validators

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#834]
## Summary of Bug

Currently we get `v2/tezos/staking/delegations/tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK`
```
{
   "code":500,
   "error":{
      "error":"Validator not found: Unable to fetch delegations list",
      "meta":{
         "Balance":"5383274",
         "Delegate":"tz1egbN6RK2bM5vt4aAZw6r9j4nL8z49bPdS"
      }
   }
}
```

This is caused by moving to a new address: https://github.com/trustwallet/assets/commit/f2948f6043cbfb6a5e3a2f81449975adc6d2e2ec#diff-7a2d5e4961dc159a8eff1a77f3f9df70, 
New address: https://github.com/trustwallet/assets/blob/f2948f6043cbfb6a5e3a2f81449975adc6d2e2ec/blockchains/tezos/validators/list.json#L186

## Expected Behavior

- Return list of current delegations
- Do not include outdated and inactive validators into `v2/tezos/staking/validators`

This also affect Cosmos validators, if they become inactive.

**Comment by Pantani** [comment]
@vikmeup If the validator isn't inside the validators map can wee show only the address, like this:

```
{
  "delegations": [
    {
      "delegator": {
        "id": "tz1egbN6RK2bM5vt4aAZw6r9j4nL8z49bPdS",
        "status": false
      },
      "value": "5383274",
      "status": "active"
    }
  ],
  "balance": "5383274",
  "address": "tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK",
  "coin": {
    "coin": 1729,
    "symbol": "XTZ",
    "name": "Tezos",
    "decimals": 6
  },
  "details": {
    "reward": {
      "annual": 6.09
    },
    "locktime": 0,
    "minimum_amount": "0",
    "type": "delegate"
  }
}
```

**Comment by vikmeup** [comment]
How does this solve an issue? Why it’s not available in the validators map? 

Reason those questions to find a solution to the problem.

**Comment by Pantani** [comment]
I going to add the validator, but to avoid we show an error when the validator not found, we can return the delegation without the validator info, it's not to solve this issue, to improve the feature

**Comment by Pantani** [comment]
My plan is to use a flag to shows if the validator is outdated or inactive, and we can set this flag without remove them

**Comment by vikmeup** [comment]
> I going to add the validator, but to avoid we show an error when the validator not found, we can return the delegation without the validator info, it's not to solve this issue, to improve the feature

There is no need for a hot fix, it only makes it worse

> My plan is to use a flag to shows if the validator is outdated or inactive, and we can set this flag without remove them

This is better solution.
