### ISSUE TITLE
Platform Unmarshal Error - invalid character 'e' looking for beginning of value

### ISSUE THREAD

**Issue by kolya182** [trustwallet/blockatlas#848]
time="2020-02-13T03:30:42Z" level=error msg="{\"error\":\"invalid character 'e' looking for beginning of value\",\"meta\":{\"method\":\"GET\",\"path\":\"ledgers/28200208\"},\"type\":\"Platform Unmarshal Error\"}" block=28200208 platform=stellar

https://horizon.stellar.org/ledgers/28200216/payments?limit=100&order=desc
level=error msg="{\"error\":\"invalid character 'e' looking for beginning of value\",\"meta\":{\"method\":\"GET\",\"path\":\"ledgers/28200216/payments\"},\"type\":\"Platform Unmarshal Error\"}" block=28200216 platform=stellar

**Comment by EnoRage** [comment]
I will take a look soon

**Comment by EnoRage** [comment]
Looks like it is an error during using GetBlockByNumber() at client.go

**Comment by EnoRage** [comment]
I tried to reproduce the error with this function at api_test.go

``` go
func TestStellar(t *testing.T) {
	client := Client{blockatlas.InitClient("https://horizon.stellar.org")}
	var wg sync.WaitGroup
	wg.Add(4999)
	for i:= 0; i < 5000; i++ {
		go runClientTest(t, client, &wg)
	}
	wg.Wait()
}

func runClientTest(t *testing.T, client Client, wg *sync.WaitGroup) {
	defer wg.Done()
	block, err := client.GetBlockByNumber(28200216)
	if err != nil {
		t.Fatal(block)
	}
	fmt.Println(block.Ledger.Sequence)
}

```

I did not get the same error as you got. Maybe it is the wrong behavior of Stellar API. Our function that is fetching this request returns an error when response cannot be marshaled to the structure. What is normal behavior. So basically it is a bug of the Stellar horizon. If it happens periodically and often - let's try to make less requests for it / change API. 

I think that current stellar codebase is ok. What do you think @kolya182 @Pantani @vikmeup

**Comment by Pantani** [comment]
@kolya182 If do you set a fixed number for stellar block observer you can see every 5 calls one returns the transaction. If do you debug, you can see a request canceled error

`net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

<img width="1617" alt="Screen Shot 2020-02-19 at 20 01 38" src="https://user-images.githubusercontent.com/2406457/74884769-b2c68600-5352-11ea-8492-d279039df1ed.png">
<img width="1238" alt="Screen Shot 2020-02-19 at 20 01 50" src="https://user-images.githubusercontent.com/2406457/74884777-b528e000-5352-11ea-9e02-eb8479974e5a.png">

**Comment by EnoRage** [comment]
Looks like it is not a repeated situation that was caused by some network latency / load error

**Comment by florindumitru** [comment]
I have the same issue
