### ISSUE TITLE
[Observer] Support pooling pending transaction for BTC like (Blockbook api) nodes

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#869]
## Problem Definition / Why?

Bitcoin is slow and requires a long wait before users will know about incoming transactions.

Support ability to send notification when new pending transaction is detected, and then when it's c confirmed.

This only applies to btc blockchain only.

**Comment by catenocrypt** [comment]
After a quick blockbook inspection, I see no practical solution:
- blockbook does track mempool (=unconfirmed, =pending) transactions
- it is possible to retrieve pending transaction when getting a transaction (by ID) or getting TXs of an address
- it is *not* possible to retrieve all mempool transactions
- there is no notification about new pending transactions

So the only way I see this possible is polling for each observed address periodically.  But this is too expensive (too many calls). and would make block-based parsing unnecessary.
I see no practical solution right now.
We would need a notification from node about each new pending transaction as it happens, but this is not expose through blockbook (no notifications at all).

**Comment by vikmeup** [comment]
ok, let's closet his for now

**Comment by catenocrypt** [comment]
I have raised an issue for blockbook, maybe they do it once :)

https://github.com/trezor/blockbook/issues/397
