### ISSUE TITLE
[Market] /ticker [GET] bad behavior

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#873]
@vikmeup found that GET /ticker is not working properly because of fixed coin at response

**Comment by vikmeup** [comment]
Can we remove this endpoint?

**Comment by EnoRage** [comment]
Let's test it on IOS / Android clients today and remove, if it will be ok

**Comment by vikmeup** [comment]
`/ticker [GET]` returns incorrect data, nobody is using it

**Comment by Pantani** [comment]
route removed
