### ISSUE TITLE
Docker Windows, Get Balances

### ISSUE THREAD

**Issue by PAkhidue** [trustwallet/blockatlas#879]
Docker:
I setup the project with Docker but many routes didn't work like swagger or bitcoin get transactions. 
When I tried to request the TRX transactions, the result was empty, but when I use the official API "blockatlas.trustwallet.com" I get the transactions. Does anyone know why?

Balances:
Is there any way to request the balance from the difference Blockchains, because I couldn't find any API Request.

**Comment by Pantani** [comment]
@PAkhidue, for bitcoin and others UTXO's blockchains you need to use `v1/<coin>/address` or `v1/<coin>/xpub` to get transactions from xpub

https://github.com/trustwallet/blockatlas/blob/master/platform/bitcoin/transaction.go#L23


There isn't a method to get the balance from the nodes, you need to request directly from the full node

**Comment by PAkhidue** [comment]
Ok thank you for the answer. Everything works as expected :).
Have a nice day/evening.
