### ISSUE TITLE
CoinGecko Markets using wrong API?

### ISSUE THREAD

**Issue by arein** [trustwallet/blockatlas#893]
## How can we help ?

[Markets uses the `v3/coins/market`](https://github.com/trustwallet/blockatlas/blob/484402aa312268427ab2890620717dec3ac7cfda/market/clients/coingecko/client.go#L51) path for CoinGecko markets. However, the CoinGecko API docs don't mention such an API. [They mention `v3/coins/markets` (notice the plural)](https://www.coingecko.com/api/documentations/v3#/coins/get_coins_markets). Is this actually working?

**Comment by Pantani** [comment]
@arein `v3`routes exist, but you are right, the API is `markets` instead `market`
