### ISSUE TITLE
[Platform] IoTex staking list does not work

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#915]
Reproduce: `{ATLAS_URL}/v2/iotex/staking/validators`
Solution: IOTEX API is not working, we need to find new alternative

**Comment by dustinxie** [comment]
fixed and redeployed https://pharos.iotex.io/v1/staking/validators
it is working now

**Comment by kolya182** [comment]
Thank you @dustinxie , working now.
