### ISSUE TITLE
Support Cosmos transactions

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#92]

**Comment by kolya182** [comment]
https://cosmos.network/rpc/#/ICS0/get_txs

**Comment by jamesscaur** [comment]
I completed the model, but I'm not sure if it fits convention. Will include in my pull request.

Transactions sent from an address can be found via 
https://stargate.cosmos.network/txs**?sender=**cosmos1rw62phusuv9vzraezr55k0vsqssvz6ed52zyrl&page=1&limit=25

Transactions sent to an address can be found via
https://stargate.cosmos.network/txs?**recipient=cosmos1rw62phusuv9vzraezr55k0vsqssvz6ed52zyrl**&page=1&limit=25

Both result in an array containing bare transaction objects.

The gas denominations don't seem to have a multiplier they need to be divided by. That's for both the root "gas_used" and "gas_wanted" values and the tx.value.fee.gas value.

Meanwhile the amounts (in both tx.value.msg.amount.amount and tx.value.fee.amount.amount) both need to be divided by 10^6 (for ATOM at least - haven't checked to see if there are other assets on Cosmos)

Example tx for comparison: https://www.mintscan.io/txs/308605FC47821D9310B1040A1351CA915FB00F2F0855F8D0B9C1F537F22E13C1
