### ISSUE TITLE
[Platform] Migrate all mocking test JSON code into separate files

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#927]
## Summary of Bug

Currently we store all JSON code inside go lang files (https://github.com/trustwallet/blockatlas/blob/master/platform/ethereum/collection_test.go#L15), which become messy and hard to write new test, better to store JSON into separate files

**Comment by EnoRage** [comment]
Can you please share your thoughts about it @kolya182 ?
I suggest just to use the consistent pattern for all platform tests and not using separete files. I did not saw many cases like this in other Golang repos like https://github.com/kubernetes/kubernetes

**Comment by EnoRage** [comment]
@catenocrypt are you ok with that? The main idea that was proposed by @vikmeup is to use .json files for mocked responses to prevent duplicates. Another reason use to simplify the way how we can reuse that files for other tests

**Comment by catenocrypt** [comment]
Some notes:
- This applies to .go test files, but also the newly-introduced .js test files (mocked with dyson)
- Response could be stored in json files, in a folder structure, where subfolders identify the API, the path, and query parameters.  E.g.
`eth/api/v1%C6addres%C60xf01010101%C7details%C8tx.json' (made-up example)
where eth/api identifies the api endpoint (from config file), filename is URL-encoded full path
- It is even possible to automate updating/creating these json files, by retrieving the responses from real endpoints.

**Comment by EnoRage** [comment]
Do we have any progress on that? @catenocrypt
