### ISSUE TITLE
[XRP] Does not have all the transactions in transaction history

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#933]
https://bithomp.com/explorer/rBaWjyDai2jqdF1aKuMKmSb7uwSfvBPVja
![2020-02-28 20 24 59](https://user-images.githubusercontent.com/22479658/75570564-6ec93480-5a68-11ea-9c95-a56554f89638.jpg)
![2020-02-28 20 25 04](https://user-images.githubusercontent.com/22479658/75570567-7092f800-5a68-11ea-9e74-34f9b745e8cf.jpg)

**Comment by kolya182** [comment]
May related to this fix https://github.com/trustwallet/blockatlas/pull/867
