### ISSUE TITLE
 [BTC] Blockbook UTXO indexing delay

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#934]
There is a significant delay in indexing transactions by xpub via Blackbook. We need to optimize the current solution and reduce the delay

There is also a problem with new block delays

**Comment by kolya182** [comment]
Looks like they have done some improvements to utxo https://github.com/trezor/blockbook/commits/master and we will need to update all instances running blockbook to see if real indexing is improved

**Comment by EnoRage** [comment]
I opened this issue after chat with @hewigovens 
@hewigovens what do you think? Is there any issue with it rn?

**Comment by hewigovens** [comment]
IMO this issue shoud not be created in blockatlas repo
