### ISSUE TITLE
Change tezos api config to https when certificate will be updated

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#955]
Currently tezos api ssl certificate is outdated, so temporary changed to http. We need to bring it back when they will resolve the issue

**Comment by robiiinos** [comment]
Looks like they solved it;
They renewed it on March, 4rd; but maybe they forgot to reload their http/s service.

```shell
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=api.tezos.id
*  start date: Mar  4 14:09:20 2020 GMT
*  expire date: Jun  2 14:09:20 2020 GMT
*  subjectAltName: host "api.tezos.id" matched cert's "api.tezos.id"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
```

**Comment by EnoRage** [comment]
Still have an error unfortunately

**Comment by zachzwei** [comment]
Is this issue still active? I have reports on Twitter for transactions not showing.
https://twitter.com/springersrock/status/1237750145028100097

**Comment by EnoRage** [comment]
"Get \"https://api.tezos.id/mooncake/mainnet/v1/transactions?account=tz1foWxaV3VQyWqFbWTERS6YDJjPT6C7jPp8\u0026n=50\u0026p=0\": x509: certificate signed by unknown authority"

It is active

**Comment by EnoRage** [comment]
> Is this issue still active? I have reports on Twitter for transactions not showing.
> https://twitter.com/springersrock/status/1237750145028100097

https://github.com/trustwallet/blockatlas/issues/956

**Comment by zachzwei** [comment]
I have this user https://tzstats.com/tz1aDaU1Fes1rusf7oCoomwJ43GvwfzpxQgL
Saying that transactions still not showing on his wallet.
Any ETA on getting this fixed?

**Comment by EnoRage** [comment]
@zachzwei 
Is one of the main priorities right now, will take a look, when will have any info, will ping you

**Comment by zachzwei** [comment]
Thanks!

**Comment by EnoRage** [comment]
We will change api to another one, this one is not working well
