### ISSUE TITLE
[Platform] Remove all real endpoints from integration and functional tests

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/blockatlas#959]
Some endpoint like fiotestnet (testnet) can broke pipeline. We need to mock each response and do not use real ones. We have status tests for that. 

- [x] domains
- [x] tokens
- [x] staking
- [x] collection
- [x] transaction (all the coins)

**Comment by EnoRage** [comment]
https://github.com/trustwallet/blockatlas/pull/963
Is a great start

**Comment by EnoRage** [comment]
https://github.com/trustwallet/blockatlas/pull/971
Transactions are done. @catenocrypt am I right?

**Comment by catenocrypt** [comment]
Correct, transactions and domain are done.

**Comment by EnoRage** [comment]
@catenocrypt added staking via #998

**Comment by EnoRage** [comment]
#1066 collections were done by @catenocrypt

**Comment by EnoRage** [comment]
Observer mocks needs to be implemented together with more detailed integration test
