### ISSUE TITLE
Add support for Decred transactions

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/blockatlas#96]

**Comment by jamesscaur** [comment]
Not sure if you have an official API to use, but dcrdata has both a custom-made and Insight API https://github.com/decred/dcrdata#insight-api

e.g.
https://explorer.dcrdata.org/api/address/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx
https://explorer.dcrdata.org/insight/api/addr/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx

**Comment by terorie** [comment]
@jamesscaur We use public/official APIs only (except ETH, that's planned) so users/devs can run their own instances of BlockAtlas.

The Decred Insight API looks like the right tool for the job.

**Comment by vikmeup** [comment]
We ended up using `Blockbook` for UTXO because `Insight` does not support bech32 addresses and limited usage of xpub/zpub. `Blockbook` is the way to go for UTXO based chains

**Comment by jamesscaur** [comment]
So if one wants to add additional UTXO based chains, make a PR to Blockbook?

**Comment by terorie** [comment]
@jamesscaur yep, BlockAtlas only supports Accounts-based chains for now. UTXO coins should be integrated with BlockBook.
