### ISSUE TITLE
[Platform] Solana support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/blockatlas#970]
https://docs.solana.com/apps/jsonrpc-api

- [x] Staking
- [ ] Block
- [ ] Transactions
- [ ] Tokens

**Comment by catenocrypt** [comment]
There is a PR in progress for Solana: https://github.com/trustwallet/blockatlas/pull/962

**Comment by hewigovens** [comment]
just commented

**Comment by EnoRage** [comment]
- [ ] Staking
- [ ] Block
- [ ] Transactions
- [ ] Tokens

**Comment by hewigovens** [comment]
Solana now has RPC for transactions: https://docs.solana.com/apps/jsonrpc-api#getconfirmedsignaturesforaddress

**Comment by EnoRage** [comment]
Moved
