### ISSUE TITLE
[Platform] Dogecoin Transaction Inputs

### ISSUE THREAD

**Issue by PAkhidue** [trustwallet/blockatlas#981]
Blockatlas has a bug when you receive Dogecoin transactions from it.
If you look at the "inputs", you will see the numbers doesn't have the decimal places and is incorrect.

Here is an example:

Dogechain API:
https://dogechain.info/api/v1/transaction/b02977b96e5c65fd807e28230375c1267ded1de7c2c43292bf36552283bc5696

Inputs sum: 10

Blockatlas API:

http://localhost:8420/v1/doge/address/DPoYGk1wGQ3uWs5G3exd9WKvVyu8weKYVA
![image](https://user-images.githubusercontent.com/45153452/77745314-558db680-701b-11ea-991e-67b5965f5f75.png)

Inputs sum: 10
But if you look at the other values, they have the decimal places, just this value not.

**Comment by kolya182** [comment]
@PAkhidue 
1. BA does support passing DOGE address in order to get transactions list
2. If query https://dogechain.info/api/v1/transaction/b02977b96e5c65fd807e28230375c1267ded1de7c2c43292bf36552283bc5696 in Postman response for the value comes back with decimals points
<img width="571" alt="Screen Shot 2020-04-01 at 4 42 22 PM" src="https://user-images.githubusercontent.com/3277207/78196595-c37d1800-7437-11ea-8de4-f147f1312e48.png">

**Comment by PAkhidue** [comment]
Hmm... I'm not sure if I explained it correctly.
So the first output is "10" from Blockatlas response (second picture in my first post).
But shouldn't it be like the second output or first input (10 * (10 ^ 8)) or how can I see if it's with or without decimal places?

9973378 would be 0,0997
10 would be 0,0000001‬

That's why I am confused.

**Comment by kolya182** [comment]
> @kolya182
> 
> Hmm... I'm not sure if I explained it correctly.
> So the first output is "10" from Blockatlas response (second picture in my first post).
> But shouldn't it be like the second output or first input (10 * (10 ^ 8)) or how can I see if it's with or without decimal places?
> 
> 9973378 would be 0,0997
> 10 would be 0,0000001‬
> 
> That's why I am confused.

So `outputs[0].value` expected to = `1000000000` (`1000000000/(10**8)=10`) isntead of `10` 
9973378/(10**8) => 0.09973378 - correct output.

Can i have xpub you used to get this transactions list ?
Trezor Blockbbok response with `1000000000` as expected by we return `10`

**Comment by PAkhidue** [comment]
I used this address for everything: DPoYGk1wGQ3uWs5G3exd9WKvVyu8weKYVA

Trezor: https://doge1.trezor.io/api/v2/address/DPoYGk1wGQ3uWs5G3exd9WKvVyu8weKYVA
Trezor tx: https://doge1.trezor.io/api/v1/tx/b02977b96e5c65fd807e28230375c1267ded1de7c2c43292bf36552283bc5696

In my first post I used the "dogechain.info" API: https://dogechain.info/api/v1/transaction/b02977b96e5c65fd807e28230375c1267ded1de7c2c43292bf36552283bc5696

Thanks for the answers and help :).

**Comment by kolya182** [comment]
@PAkhidue We want to close this issue, could you send your xpub if yo uhave to my telegram t.me/mykola ?
