### ISSUE TITLE
FIO transaction history support

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/blockatlas#982]
This is currently not implemented, only FIO lookup is implemented.

**Comment by catenocrypt** [comment]
FIO API currently has no API for transaction history (due to performance ressons?).
Explorer shows history for an account (not address aka. public key), see e.g. 
  https://explorer.fioprotocol.io/account/f5axfpgffiqz
For mainnet info, see:   https://github.com/fioprotocol/fio.mainnet

**Comment by hewigovens** [comment]
@catenocrypt can you try those api endpoints who have enabled history plugin? https://github.com/fioprotocol/fio.mainnet#history-v1

Docs:
https://developers.eos.io/manuals/eos/latest/nodeos/plugins/history_api_plugin/index

**Comment by catenocrypt** [comment]
curl --request POST --url https://fio.greymass.com/v1/history/get_transaction --data '{"id": "930d1d3cf8988b39b5f64b64e9d61314a3e05a155d9e3505bdf863aab1adddf3"}'

**Comment by catenocrypt** [comment]
Implementation done PR #984 .

**Comment by catenocrypt** [comment]
Merged.  See e.g. curl https://blockatlas.trustwallet.com/v1/fio/FIO7Q3XfQ2ocGP1zYst6Sfx5qrsiZ865Cu8So2atrub9JN94so7gt
(once deployed)
